# Generated by Django 4.2.15 on 2024-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minutes', models.IntegerField()),
                ('nutrition', models.JSONField()),
                ('steps', models.JSONField()),
                ('description', models.TextField()),
                ('ingredients', models.JSONField()),
            ],
        ),
    ]
